apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: foodapp
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: foodapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # Minikube/Docker Desktop için varsayılan yeterli
  # GKE: standard, premium-rwo
  # EKS: gp2, gp3
  # AKS: managed-premium
